name: PostMerge
on:
  pull_request:
    types: [closed]

jobs:
  postMerge:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/checkout@v3
        with:
          ref: fluor
      - name: Run a one-line script
        run: git cherry-pick bcc3e87
